apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: warehouse
  labels:
    app-label: warehouse-label
spec:
  ports:
    - port: 8000
      name: plaintext
      targetPort: 8000
  selector:
    app-label: warehouse-label
  loadBalancerIP: $APP_IP
  type: LoadBalancer