apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
  labels:
    app-label: warehouse-label
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app-label: warehouse-label
  template:
    metadata:
      labels:
        app-label: warehouse-label
    spec:
      containers:
      - name: warehouse-app
        image: cr.yandex/$REGISTRY_ID/warehouse:v1
        env:
          - name: DB_NAME
            value: $DB_NAME
          - name: DB_USER_NAME
            value: "$DB_USER_NAME"
          - name: DB_PASSWORD
            value: "$DB_PASSWORD"
          - name: DB_HOST
            value: "$DB_HOST"
          - name: DB_PORT
            value: "$DB_PORT"
          - name: JWT_SECRET_KEY
            value: "$JWT_SECRET_KEY"