"""create_users_carts_table

Revision ID: 757125b45ee4
Revises: 6b1a39feedec
Create Date: 2022-10-29 21:56:31.777182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757125b45ee4'
down_revision = '6b1a39feedec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_carts_id'), 'users_carts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_carts_id'), table_name='users_carts')
    op.drop_table('users_carts')
    # ### end Alembic commands ###
