name: GitHub actions

env:
  YC_AUTH_KEY_JSON: ${{ secrets.YC_AUTH_KEY_JSON }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  K8S_ID: ${{ secrets.K8S_ID }}
  
on: workflow_dispatch

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yandex Cloud
        run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Create key.json
        run: |
          echo $YC_AUTH_KEY_JSON > key.json
          cat key.json
      - name: Configure profile for yc
        run: |
          ~/yandex-cloud/bin/yc config profile create bitbucket
          ~/yandex-cloud/bin/yc config set service-account-key key.json
      - name: Set up cloud-id
        run: ~/yandex-cloud/bin/yc config set cloud-id $CLOUD_ID
      - name: Set up folder-id
        run: ~/yandex-cloud/bin/yc config set folder-id $FOLDER_ID
      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          mv ./kubectl ~/
          chmod +x ~/kubectl
      - name: Set up k8s credentials
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id=$K8S_ID --external
      - name: Move kubectl file and config to k8s folder
        run: mkdir ~/k8s && mv ~/kubectl ~/k8s && mv ~/.kube ~/k8s
      - uses: actions/upload-artifact@master
        with:
          name: kubectl
          path: ~/k8s

  build:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: kubectl
          path: ~/k8s
      - name: Move k8s files from k8s
        run: mv ~/k8s/* ~/
      - name: Make kubectl executable
        run: chmod +x ~/kubectl
      - name: Get all content of home path
        run: ls -l ~/
      - name: Get all k8s resources
        run: ~/kubectl get all --kubeconfig ~/.kube/config
