name: GitHub actions

env:
  YC_AUTH_KEY_JSON: ${{ secrets.YC_AUTH_KEY_JSON }}
  
on: workflow_dispatch

jobs:
  set-up-yc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yandex Cloud
        run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Activate yc
        run: exec bash -l
      - name: Create key.json
        run: |
          echo $YC_AUTH_KEY_JSON > key.json
          cat key.json
      - name: Configure profile for yc
        run: |
          yc config profile create bitbucket
          yc config set service-account-key key.json
          yc config profile list
