name: GitHub actions

env:
  YC_AUTH_KEY_JSON: ${{ secrets.YC_AUTH_KEY_JSON }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  
on: workflow_dispatch

jobs:
  set-up-yc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yandex Cloud
        run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Create key.json
        run: |
          echo $YC_AUTH_KEY_JSON > key.json
          cat key.json
      - name: Check yc installed
        run: ls ~/
      - name: Configure profile for yc
        run: |
          ~/yandex-cloud/bin/yc config profile create bitbucket
          ~/yandex-cloud/bin/yc config set service-account-key key.json
      - name: Set up cloud-id
        run: ~/yandex-cloud/bin/yc config set cloud-id $CLOUD_ID
      - name: Set up folder-id
        run: ~/yandex-cloud/bin/yc config set folder-id $FOLDER_ID
      - name: Get k8s cluster
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster list

  test-another-task:
    runs-on: ubuntu-latest
    steps:
      - name: test yc
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster list
