name: GitHub actions

env:
  YC_AUTH_KEY_JSON: ${{ secrets.YC_AUTH_KEY_JSON }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  K8S_ID: ${{ secrets.K8S_ID }}
  REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
  APPLICATION_ENV_DATA: ${{ secrets.APPLICATION_ENV_DATA }}

#on: workflow_dispatch

on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yandex Cloud
        run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Upload yc artifact
        uses: actions/upload-artifact@master
        with:
          name: yc
          path: ~/yandex-cloud
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download yc artifact
        uses: actions/download-artifact@master
        with:
          name: yc
      - name: Create key.json
        run: |
          echo $YC_AUTH_KEY_JSON > key.json
          cat key.json
      - name: Configure profile for yc
        run: |
          ~/yandex-cloud/bin/yc config profile create bitbucket
          ~/yandex-cloud/bin/yc config set service-account-key key.json
      - name: Set up cloud-id
        run: ~/yandex-cloud/bin/yc config set cloud-id $CLOUD_ID
      - name: Set up folder-id
        run: ~/yandex-cloud/bin/yc config set folder-id $FOLDER_ID
      - name: Set up k8s credentials
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id=$K8S_ID --external
      - name: Set up docker registry
        run: ~/yandex-cloud/bin/yc container registry configure-docker
      - name: Use yc
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster list
      - name: Use kubectl
        run: kubectl get all
      - name: Set up env variables
        run: echo $APPLICATION_ENV_DATA > ./prod/.env
      - name: Build docker image
        run: docker build . --file Dockerfile --tag cr.yandex/$REGISTRY_ID/warehouse:v1
      - name: Push docker image
        run: docker push cr.yandex/$REGISTRY_ID/warehouse:v1
      - name: Deploy kustomization
        run: kubectl apply -k ./prod
      - name: Deploy docker image
        run: kubectl apply -f ./prod/warehouse.yaml