name: GitHub actions

env:
  YC_AUTH_KEY_JSON: ${{ secrets.YC_AUTH_KEY_JSON }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  K8S_ID: ${{ secrets.K8S_ID }}
  REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
  APPLICATION_ENV_DATA: ${{ secrets.APPLICATION_ENV_DATA }}
  APP_IP: ${{ secrets.APP_IP }}

#on: workflow_dispatch

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # set up
      - name: Install Yandex Cloud
        run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Create key.json
        run: |
          echo $YC_AUTH_KEY_JSON > key.json
          cat key.json
      - name: Configure profile for yc
        run: |
          ~/yandex-cloud/bin/yc config profile create bitbucket
          ~/yandex-cloud/bin/yc config set service-account-key key.json
      - name: Set up cloud-id
        run: ~/yandex-cloud/bin/yc config set cloud-id $CLOUD_ID
      - name: Set up folder-id
        run: ~/yandex-cloud/bin/yc config set folder-id $FOLDER_ID
      - name: Set up k8s credentials
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id=$K8S_ID --external
      - name: Set up docker registry
        run: cat ./key.json | docker login --username json_key --password-stdin cr.yandex

      # build
      - name: Set up env variables
        run: echo $APPLICATION_ENV_DATA > ./prod/.env && . ./prod/.env
      - name: Build
        run: docker build . --file Dockerfile --tag cr.yandex/$REGISTRY_ID/warehouse:v1

      # test
      - name: Tests
        run: echo "Here will be running tests!"

      # deploy
      - name: Push docker image
        run: docker push cr.yandex/$REGISTRY_ID/warehouse:v1
      - name: Deploy application
        run: envsubst < ./prod/warehouse.yaml | kubectl apply -f -
      - name: Run load balancer
        run: envsubst < ./prod/load-balancer.yaml | kubectl apply -f -
