name: GitHub actions

env:
  YC_AUTH_KEY_JSON: ${{ secrets.YC_AUTH_KEY_JSON }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  K8S_ID: ${{ secrets.K8S_ID }}
  
#on: workflow_dispatch

on:
  push:
    branches: [ master ]

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yandex Cloud
        run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - name: Create key.json
        run: |
          echo $YC_AUTH_KEY_JSON > key.json
          cat key.json
      - name: Configure profile for yc
        run: |
          ~/yandex-cloud/bin/yc config profile create bitbucket
          ~/yandex-cloud/bin/yc config set service-account-key key.json
      - name: Set up cloud-id
        run: ~/yandex-cloud/bin/yc config set cloud-id $CLOUD_ID
      - name: Set up folder-id
        run: ~/yandex-cloud/bin/yc config set folder-id $FOLDER_ID
      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          mv ./kubectl ~/
          chmod +x ~/kubectl
      - name: Set up k8s credentials
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id=$K8S_ID --external
      - name: Set up docker registry
        run: ~/yandex-cloud/bin/yc container registry configure-docker
      - uses: actions/upload-artifact@master
        with:
          name: .kube
          path: ~/.kube
      - uses: actions/upload-artifact@master
        with:
          name: kubectl
          path: ~/kubectl

  build:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Move files from artifact to default folder
        run: mv ./.kube ~/ && mv ./kubectl/kubectl ~/
      - name: Make kubectl executable
        run: chmod +x ~/kubectl
      - name: Get all k8s resources
        run: ~/kubectl get all --kubeconfig ~/.kube/config
